### PR TITLE
Use lodash-es for ES modules

### LINKED ISSUE #1286: 2.x requires unstated dependency @types/lodash.flowright
**Intended outcome:**
Upgrading from 1.x release to the 2.x release. 

**Actual outcome:**
```
Error at node_modules/react-apollo/browser.d.ts:6:26: Could not find a declaration file for module 'lodash.flowright'. '/Users/x/x/node_modules/lodash.flowright/index.js' implicitly hasan 'any' type.
  Try `npm install @types/lodash.flowright` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash.flowright';`
```

**How to reproduce the issue:**

Install react apollo in a typescript project and run tsc

**Version**
- apollo-client@2.0.1
- react-apollo@2.0.0

### PR DESCRIPTION
**Pull request by corydeppen**
Resolves #1286

### CODE REVIEW

**Comment by corydeppen** [comment]
Sorry for the noise - I mistakenly ran `compile` instead of `test` prior to committing so I didn't see the issue until it was too late. It appears the problem is that `lodash-es` ships ES modules, which aren't transformed by Jest. I'm hoping [solution 3](https://medium.com/@martin_hotell/tree-shake-lodash-with-webpack-jest-and-typescript-2734fa13b5cd#d898) will solve this issue.

**Comment by jbaxleyiii** [comment]
@corydeppen what is lodash-es?

**Comment by jbaxleyiii** [comment]
Ah! I see https://github.com/apollographql/react-apollo/issues/1286#issuecomment-340309548

Can you take a look at the CI failure? And add a changelog and I'd love to merge and release this!

**Comment by corydeppen** [comment]
@jbaxleyiii Including functions from the specific lodash-es modules increased the size of the bundle. I didn't want to tweak the bundlesize threshold until I knew you were okay with the approach.

**Comment by bjrnt** [comment]
Is there any way we could get this merged? Seems like this issue is holding up more than 20 teams from upgrading to v.2 based on the reactions to #1286.

**Comment by jbaxleyiii** [comment]
@corydeppen I'm really concerned about including all of lodash even with the `es` version for people who don't have bundlers that can remove it. 😢 

I wonder if there is another way?

**Comment by HugoGiraudel** [comment]
*I posted this comment on a commit but I cannot seem to find it anymore so allow me to submit it again here.*

This change (apparently published in `2.0.3`) seems to cause an error in our build:

```
SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /goldfish/node_modules/react-apollo/react-apollo.umd.js:2:123
/goldfish/node_modules/lodash-es/pick.js:1
(function (exports, require, module, __filename, __dirname) { import basePick from './_basePick.js';
```

Did we miss something maybe? 

Thank you!

**Comment by doomsower** [comment]
I get same error here after update, but only in jest tests. The app itself builds and runs fine
I'm using [create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript)

Here is my `tsconfig.json`:

```json
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es7", "dom", "esnext.asynciterable"],
    "sourceMap": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowSyntheticDefaultImports": false,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true
  },
  "exclude": [
    "__mocks__",
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}

```

And for tests, `tsconfig.test.json`:

```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "module": "commonjs"
  }
}
```

**Comment by doomsower** [comment]
From this comment https://github.com/facebookincubator/create-react-app/issues/3001#issuecomment-324623459 I conclude that this problem should also affect regular `create-react-app` projects, not just typescript fork.

I see that in this PR @corydeppen works around this with `transformIgnorePatterns`, but this is impossible with `create-react-app` projects

**Comment by lednhatkhanh** [comment]
Since the fix has been rolled back, now I get the lodash error again...

**Comment by danielrasmuson** [comment]
Any known workarounds while this issue gets resolved?

**Comment by kandros** [comment]
still looking for a workaroud, any idea?

**Pull request merged**
