### PR TITLE
Add support for client in options

### PR DESCRIPTION
**Pull request by flexzuu**
Adds support for client in graphql HoC to support usecases with more than one ApolloClient

Proposal and discussion: [#464](https://github.com/apollographql/react-apollo/issues/464)
Other relevant PR: [#481](https://github.com/apollographql/react-apollo/pull/481)
Docs: WIP

TODO:

- [x] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all tests and linter rules pass
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Update CHANGELOG.md with your change
- [ ] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by flexzuu** [comment]
Tests seem to not only dont work correctly on my setup but CI aswell: 

```
No tests found
In /home/travis/build/apollographql/react-apollo
  2274 files checked.
  testMatch:  - 2274 matches
  testPathIgnorePatterns: /node_modules/ - 81 matches
  testRegex: <rootDir>/test/.*.test.(ts|tsx|js)$ - 0 matches
Pattern: "" - 0 matches
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|

```

**Comment by jbaxleyiii** [comment]
@flexzuu that is odd, can you try rebasing off of #695? It will be in master soon and works locally and on the CI for me?

**Comment by flexzuu** [comment]
@jbaxleyiii hey thanks for merging i found some more stuff i needed to edit to finish this feature. will push this now. Will look into the failing tests and add some more tests if needed.
Some feedback about the PR overall is appreciated (It is my first "bigger" contribution to a OSS project)

**Comment by flexzuu** [comment]
Will work on adding test for ne new option next. After that docs and changelog will be added.

**Comment by flexzuu** [comment]
@jbaxleyiii Hey thanks for mergeing. I will start working on the docks in my free time.

**Comment by ads1018** [comment]
This rocks! Until the documentation gets updated would one of you mind sharing what the syntax looks like for adding more than one client?

**Comment by flexzuu** [comment]
```
graphql(query, {
  options: props => ({ client: ... }),
})(MyComponent)
```

Check back with me again if you have anymore questions. I am relatively busy right know will work on the docs next week.

**Comment by ads1018** [comment]
Neat. So you can initialize a bunch of clients and then decide which one you want to use on a component by component basis?

**Comment by ramrodo** [comment]
Hey @flexzuu thanks for this contribution, I'm trying to implement this but I can't involucrate the two ApolloClient instances, do you have the documentation somewhere?

**Comment by vjpr** [comment]
@flexzuu Could we get some docs for this please?

**Comment by flexzuu** [comment]
@vjpr i completely reworked the idea and will publish some stuff about how to use it in the future.

The basic idea is that you don't use the option apollo provides but just use 2 providers and the standard graphql hoc then you would add in 2 tunnels that reexpose the context under a namespaced key. You can then use something like recomposes fromContext and withContext to connect to the namespaced context and reexpose it under the original context this way you can use the vanilla provider and vanilla hoc but you can use as many providers as you like. I will try to build a Tunnel lib out of this but if first need to see how well this approach hold up against real world use cases.

**Pull request merged**
