### PR TITLE
fix: Move constructor initializing of props to componentWillMount

### PR DESCRIPTION
**Pull request by drager**
React outputs setState warnings (constructor side-effects are an anti-pattern), because of that initializing of props in the constructor and by moving that code to componentWillMount fixes that.

### CODE REVIEW

**Comment by calebmer** [comment]
We don’t set state anywhere in that code 😣

Could you make a small reproduction with [`react-apollo-error-template`](https://github.com/apollographql/react-apollo-error-template) so I can see where the error is being triggered?

**Comment by calebmer** [comment]
It looks like this error was reproduced in this issue: https://github.com/apollographql/react-apollo/issues/509

@drager can you confirm this is the same issue?

I want to take some time to look at the reproduction and understand what is really going on to see if we can get a more specific fix.

**Comment by calebmer** [comment]
After more investigation in https://github.com/apollographql/react-apollo/issues/509 it looks like this does indeed fix the problem. I cleaned it up a little, @drager could you add a changelog entry and then we can merge? 😊

**Comment by drager** [comment]
@calebmer: Thanks, sorry for the late answer but great that #509 could confirm this issue. Will add a changelog entry as soon as possible. :)

**Comment by morgante** [comment]
When can we expect this to be released? Has anyone found a workaround for now?

**Comment by calebmer** [comment]
Released in `0.13.3` 🎉

**Pull request merged**
