### PR TITLE
Changing React import in MockedProvider

### PR DESCRIPTION
**Pull request by mkaraula**
Importing React with import * as React in MockedProvider fixes
apollographql/apollo-client#5306

### CODE REVIEW

**Comment by maxcan** [comment]
cc @hwillson

**Comment by seansfkelley** [comment]
Related: https://github.com/apollographql/react-apollo/issues/3537.

**Comment by mkaraula** [comment]
@hwillson did you managed to look into this?

**Comment by mkaraula** [comment]
@hwillson ping :)

**Comment by mkaraula** [comment]
@hwillson another ping 😅

**Comment by mkaraula** [comment]
Closing this PR because it can not be merged anymore. 

https://github.com/apollographql/apollo-client/issues/5306#issuecomment-591430312

**Pull request closed without merging**
