### PR TITLE
Resubscribe after error -- apollo-client issue 2513

### PR DESCRIPTION
**Pull request by wdimiceli**
This is a fairly minimal fix for React components ceasing to get updates after an error occurs in a query.  It happens due to the way observables work.. they will terminate a subscription after the error handler is called.  Without going through and reconsidering all of the subscription logic between react-apollo and the client, simply resubscribing on error seems like the simplest way to get it working again.  A unit test was written to cover this scenario.

Here is the most relevant issue:
https://github.com/apollographql/apollo-client/issues/2513
I have seen several others which might be resolved with this fix.

### CODE REVIEW

**Comment by rosskevin** [comment]
@excitement-engineer if this looks good, we need to mirror the tests and changes to `Query`.

@wdimiceli if you want to increase bundle maxSize in the package.json and push it that will solve the build error.  4.8 will be fine.

**Comment by edorivai** [comment]
Is there a chance this will be released on NPM any time soon? Pretty, pretty please :smile:

**Comment by rosskevin** [comment]
Please check the releases tab before posting.  We are going to try and release more frequently and this most certainly has been released (though strangely danger did not require a changelog entry for it).

Try the 2.1 beta: https://github.com/apollographql/react-apollo/releases

**Comment by edorivai** [comment]
@rosskevin Sorry, wasn't aware of the beta releases, just checked npm stable. Thanks!

**Comment by nfantone** [comment]
Unfortunately, this didn't resolve https://github.com/apollographql/react-apollo/issues/1385 for me 😞 . However, installing the beta release of `react-apollo` + latest `apollo-client@2.2.2` + `apollo-cache-in-memory@1.1.7` make requests work again after an error and the `loading` was being set correctly.

**Comment by AndrewHenderson** [comment]
@nfantone I have upgraded to all of those versions with `react-apollo@2.1.0-beta.2`.

I'm finding that when their is an error in a component, the loading prop is false, however none of the props are passed to the component.

I'm using a sub-resolver and testing when there is an error in that single function.

Everything works as expected in GraphQL – when there is an error, that single property is `null` and the GraphQL error is returned on the response.

However, because there is an error, none of the parent props, the partial result that returned, gets passed to the component 😕

**Comment by edorivai** [comment]
@AndrewHenderson I might be misunderstanding, but partial results sound like a job for `errorPolicy`: https://www.apollographql.com/docs/react/features/error-handling.html#policies

**Comment by AndrewHenderson** [comment]
@edorivai That’s exactly the setting I needed. I completely missed that. Thank you! 😁

**Comment by nfantone** [comment]
@AndrewHenderson Actually, what I'm seeing is that now the `loading` and `error` properties are working fine, but - on error, `data` continues to hold the _latest correctly fetched_ data, instead of what was actually returned by the `/graphql` response.

@edorivai Would you have any input on this? Would this be the intended functionality?

**Comment by AndrewHenderson** [comment]
@edorivai I tried using errorPolicy, but I’m still experiencing what @nfantone has described.

I thought it might work using the new Query component, but don’t see an errorPolicy propType for that new component.

**Comment by edorivai** [comment]
Hey guys, sorry to disappoint you, but I'm no authority on this lib 😅,
just another user.

@AndrewHenderson I didn't try it with the Query component yet. But I would
expect it should be possible to implement if it isn't yet.

**Comment by tmeasday** [comment]
I could be misunderstanding but I suspect this does not work with polling queries (I haven't been able to make it work), because `apollo-client` does not [resume polling after a network error](https://github.com/apollographql/apollo-client/issues/1099#issuecomment-299603974)

Perhaps if the query has `pollInterval` set `react-apollo` should also re-create the `observableQuery` on error also?

**Comment by 404sand808s** [comment]
Hi guys, checking in to see if anybody knows when this might be released — desperately need this to re-establish connection after an error (to give the user a way to reload). Thanks, and sorry for the bump.

**Comment by iamrommel** [comment]
This is really breaking, we are are using react-native and apollo, and whenever i go to elevator (which most of the time has not data connection), my app gets error, and even when i get back to wifi connection, my connection cannot be recovered. Correct data are being pull from the server, but the component are not updated

**Pull request merged**
