### PR TITLE
Fixed inconsistency in naming of the prop for the subscription

### PR DESCRIPTION
**Pull request by excitement-engineer**
There is an inconsistency in the names of the props for the documents:

```
<Query query={} />
<Mutation mutation={} />
<Subscription query={} />
```

The name of the prop for the `Subscription` component is inconsistent with the others. Therefore, I propose that we call the prop `subscription` instead of `query`

```
<Subscription subscription={} />
```

### CODE REVIEW

**Comment by excitement-engineer** [comment]
Curious to hear your thoughts @jbaxleyiii

**Comment by fbartho** [comment]
Counter-proposal: move the `mutation` prop to be `query={`. They're all GraphQL queries.

**Comment by excitement-engineer** [comment]
This is also an option:) I'm happy as long as it is consistent!

**Comment by jbaxleyiii** [comment]
I think we can either go `query` => `operation` or `query` => `subscription`. I think subscription will lead to the least confusion when looking back at old code, especially if you extend the component class and give it another name (like in TS)

**Pull request merged**
