### PR TITLE
Allow launching jest in the vscode debugger

### PR DESCRIPTION
**Pull request by rricard**
We were able to do that previously with mocha

### CODE REVIEW

**Comment by rricard** [comment]
I still have issues remapping to the typescript...

**Comment by tmeasday** [comment]
> I still have issues remapping to the typescript...

I'm not sure what this means @rricard?

**Comment by rricard** [comment]
There is no sourcemapping with ts in jest right now, I have to fix that first.

**Comment by stubailo** [comment]
Yeah looks like Jest has some pros and cons, compared to the super complex config we had before :P

**Comment by rricard** [comment]
@stubailo I'll go through jest options and find something, I'm sure we can make that work!

**Comment by jbaxleyiii** [comment]
@rricard how can I help with this?

**Comment by rricard** [comment]
@jbaxleyiii reminding me about this issue, which you did, so let's get back to it!

**Comment by rricard** [comment]
@jbaxleyiii ok, well, I hit a wall, I'm not good enough with the tsc to understand what's wrong... Seems like vscode is unable to find the generated sources from the preprocessor. At this point, I tried many things, I'm not even sure `preprocessor.js` is even executed...

**Comment by jbaxleyiii** [comment]
@rricard thanks for the hard fighting here! If I can find some time I'll keep looking!

**Comment by helfer** [comment]
@rricard what's currently the blocker here?

**Comment by rricard** [comment]
@helfer I don't see how to control the output of the jest transform to output sourcemaps that the debugger can use...

**Comment by helfer** [comment]
@calebmer if you have time to figure this one out, we should merge it, otherwise we'll probably have to close it.

**Comment by calebmer** [comment]
Try using [`ts-jest`](http://npmjs.com/ts-jest). It has correct source map support for TypeScript.

**Comment by calebmer** [comment]
We are going to close this for now.

**Pull request closed without merging**
