### PR TITLE
Fixed bugs around invariants

### PR DESCRIPTION
**Pull request by jimmyhmiller**
This fixes the problems identified in #453.

### CODE REVIEW

**Comment by calebmer** [comment]
Looks like the CI failure was accidental. Restarted CI 👍

**Comment by stubailo** [comment]
@calebmer CI has passed!

**Comment by calebmer** [comment]
Could we get a changelog entry @jimmyhmiller? After that it should be good to merge 😊

**Comment by helfer** [comment]
I'll merge and add the changelog entry when I release. Thanks @jimmyhmiller !

**Pull request merged**
