### PR TITLE
WIP: Include peers

### PR DESCRIPTION
**Pull request by helfer**
TODO:

- [x] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change
- [x] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by jaydenseric** [comment]
@helfer After updating to v0.13.0, `ApolloClient` or `ApolloClient` is not available for import. They simply don't appear in the compiled dist.

**Comment by helfer** [comment]
@jaydenseric Yeah, I figured that out today as well. I'll have to dig into it.

**Comment by helfer** [comment]
@jaydenseric actually, I'm not sure why `dist` is included, because in package.json main is specified as `lib/index.js`. My guess as to why the exports are not included is that maybe the bundler uses the `browser` field instead, which is `lib/browser.js`, but as far as I can tell react-apollo's build setup doesn't actually write to that file!

cc @calebmer @jbaxleyiii

**Comment by jaydenseric** [comment]
I can't be much help here because it's TypeScript :(

While messing around with this stuff, what are the chances of adding a  [package.json `module`](https://github.com/rollup/rollup/wiki/pkg.module) entry for modern tools (such as Webpack 2) to consume ESM?

**Comment by jaydenseric** [comment]
Created a proper issue regarding the `module` enhancement: https://github.com/apollographql/apollo/issues/78.

**Comment by calebmer** [comment]
Yeah, I’m not sure how the build is setup in `react-apollo`. I need to take a look at the builds for both `apollo-client` and `react-apollo` 😣

**Comment by helfer** [comment]
@calebmer: please focus on react-apollo first, because the build here seems somewhat broken while for Apollo Client it's still working.

**Comment by calebmer** [comment]
@helfer do we want to schedule this as a fix for 1.0?

**Comment by helfer** [comment]
Yes, for this repo definitely.

**Comment by helfer** [comment]
@calebmer I was stupid and should have put the exports in `browser.ts` instead of `index.ts`. Feel free to ignore what I said before.

**Pull request merged**
