### PR TITLE
Update lastResult whenever data changes to ensure components re-rende…

### PR DESCRIPTION
**Pull request by Glennrs**
I've been unable to write a test case to reproduce this scenario, however, the logic is fairly simple to follow. I'm happy to be informed if I'm missing something and this PR is not required. Scenario is:

1) Component renders with value from cache, which sets lastResult.
2) Value of cache is set to another value. Component re-renders.
3) Value is set back to the original value, therefore shallowEquals does not pass since lastResult is fixed to the original render.

This PR ensures that lastResult is updated if set, when new data is available.

Fixes https://github.com/apollographql/react-apollo/issues/2857.
Fixes https://github.com/apollographql/react-apollo/issues/2887.

### CODE REVIEW

**Comment by hwillson** [comment]
Thanks for submitting this PR @Glennrs. We can't accept this PR as it stands currently, as we have no way to verify that it's fixing a problem. A test showing what this fixes (to help avoid regressions), or a  small runnable reproduction that demonstrates how this is a problem, would definitely help. I'll close this for now, but to help push the discussion forward, I'd suggest opening a new issue with as many details as you can provide that shows how this is a problem. Once we've been able to confirm this is an issue, we'll then be ready to accept a PR. Thanks!

**Comment by Glennrs** [comment]
The following Gist has a repro for the issue. You can see that after the Query component has its properties updated, it will set lastResult to true and subsequently always early out when the value is set back to true again (meaning it remains in a state where it renders false).

**Comment by hwillson** [comment]
Re-opening as this issue has been demonstrated by the reproduction in https://github.com/apollographql/react-apollo/issues/2887. I'll add a regression test, then get this merged.

**Comment by hwillson** [comment]
I've updated the original PR message to reference a few issues this will help fix, but I'm sure there are others that this will help with (either directly or indirectly), like https://github.com/apollographql/react-apollo/issues/1931.

**Comment by yloeza** [comment]
@hwillson when are you guys planning to release this? is it going to be just a patch version?

**Comment by mac-s-g** [comment]
also hoping to test this out!

**Comment by mac-s-g** [comment]
update:
2.4.1 has other issues... mainly, the issue with data getting set to an empty object (resolved @ ^2.5).  so, i gotta move back to 2.5.4 and wait for the release.  loading states will be a little clunky til then.

maybe a good time to give a shout out to all the contributors on this project.
it's an AWESOME module. really amazing work.  thank you for creating and maintaining it!

**Pull request merged**
