### PR TITLE
TASK: Provide errors to component when error Policy is "all"

### PR DESCRIPTION
**Pull request by Torsten85**
The docs say that "any errors reported will come under an error prop along side the data returned from the cache or server."  (https://www.apollographql.com/docs/react/features/error-handling.html)

This PR will provide those errors to the component.

To make it work, another PR is mandatory: https://github.com/apollographql/apollo-client/pull/2956

### CODE REVIEW

**Comment by Torsten85** [comment]
Resolves #1389

**Comment by twelve17** [comment]
@Torsten85 does [this line](https://github.com/Torsten85/react-apollo/blob/2c2e542e81a042961e7f3c1993bdc39d391c238f/src/graphql.tsx#L600) also need to be changed to look for `errors` (plural)?

```
const { loading, error, networkStatus } = currentResult;
```

**Comment by Torsten85** [comment]
@twelve17 No, I'm getting the `errors` directly from the currentResult inside `calculateResultProps` because `errors` and `data` are along side each other.

Thats how I assume the docs would want it ;) 

If `errors` should be within `data`, then the line you mentioned would be the point to add it. But this would result in `data.error` and `data.errors` which seems wrong.

**Comment by twelve17** [comment]
@Torsten85 I don't believe `currentResult` is `data`, but the result form the server, which would have `data` and `errors`, thus that code is not trying to get `errors` from inside `data`.  At least that is not what I observed when debugging that code (not sure if you saw the screen shot in the issue thread).

**Comment by Torsten85** [comment]
The tests show that I've missed quite a lot of cases there so I have to invest more time in this. But before I start I need an "official statement" on how the result should look like. The docs are not very clear: "Any errors reported will come under an error prop along side the data returned from the cache or server."

**Comment by twelve17** [comment]
@Torsten85 One important distinction is what the apollo *client* itself will return to the component, vs. what the apollo *server* returns to the client.  The bug, as I understand it at the moment, is that the client is not searching in the proper place for the server's response (which exists in the `errors` (plural) property).

Since now we have a divergence in property naming, I no longer know what the *client* should return to the component.  I believe this is what you are referring to here (as well as in a previous comment).  

In the case of server `errors`, should the client provide a `errors` (plural) component, which is also an array, similar to what the server returns?  Or should it return that same array in the `error` property, which is not always an array (in the case of network errors, for example, where there is no server response).  

Indeed, we need an official statement.

**Comment by jbaxleyiii** [comment]
@Torsten85 thanks for the work on this one! The fix for this actually was merged in (but not released on the beta channel yet). Should be out this week!

**Comment by twelve17** [comment]
@jbaxleyiii Can you let us know what release the fix is in? I'm on react-apollo 2.4 and am still seeing the behavior [in this screenshot|https://github.com/apollographql/react-apollo/issues/1389#issuecomment-363018389], and not seeing the error being set to the `error` property.

**Comment by menkveldj** [comment]
June 21, still seeing the issue...

**Pull request closed without merging**
