### PR TITLE
Add onCompleted prop to Query

### PR DESCRIPTION
**Pull request by jeshep**
Allows a function to be passed into the Query component that will be run once the query has completed. Useful for modifying the local state with data from a query, e.g. initialize the select value to the first item from the query results.

Reference Issue: #1862 

Not sure if there is a better place in the Query component to call the provided onCompleted function, but this implementation seems to work.

### Checklist:

* [] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
* [x] Make sure all of the significant new logic is covered by tests
* [ ] If this was a change that affects the external API used in GitHunt-React, update GitHunt-React and post a link to the PR in the discussion.

### CODE REVIEW

**Comment by tab00** [comment]
I hope this will be merged soon, as I actually need it right at this moment.

**Comment by tab00** [comment]
What's the hold up? This should have been in the original implementation.

**Comment by ajoslin** [comment]
Ping. This needs to happen.

**Comment by jimshepherd** [comment]
Added onError prop to the PR.

Would be nice to get some feedback on this PR from the maintainers.

**Comment by ajoslin** [comment]
Apollo devs, how can we support in getting this merged? This would really help.

**Comment by jarommadsen** [comment]
Would love to see this make it through. Haven't peeked at the changes yet but will onCompleted be fired on fetchMore?

**Comment by jimshepherd** [comment]
Awesome! Glad I could contribute.

**Comment by ajoslin** [comment]
🎉

**Pull request merged**
