### PR TITLE
Fix React Component detection

### PR DESCRIPTION
**Pull request by edorivai**
Solves https://github.com/apollographql/react-apollo/issues/1595

@jbaxleyiii @leoasis

### CODE REVIEW

**Comment by leoasis** [comment]
@edorivai mind adding a test for this? It would be super useful so that we don't cause a regression accidentally.

Also, add an entry in the changelog that mentions this fix.

**Comment by edorivai** [comment]
@leoasis 2 questions:

First, where in the changelog should I add the entry? Under `2.1.0-beta.0`, or rather somewhere else?

Second, I'm having a bit of trouble with writing the test, I tried just copying over the `basic classes` test, and changing the `render` to be on the instance, instead of on the prototype:

```typescript
      it('basic classes with render on instance', () => {
        let elementCount = 0;
        class MyComponent extends React.Component<any, any> {
          render = () => {
            return <div>{_.times(this.props.n, i => <span key={i} />)}</div>;
          }
        }
        walkTree(<MyComponent n={5} />, {}, element => {
          elementCount += 1;
        });
        expect(elementCount).toEqual(7);
      });
```

However, Typescript is too smart, and points out the "mistake": 
```
TS2424: Class 'Component<any, any>' defines instance member function 'render', but extended class 'MyComponent' defines it as instance member property.
```

I tried just rendering the `<Link/>` element from `react-scroll`, which does the job. But I can imagine you'd prefer not to add `react-scroll` as a dev dependency.

Do you have any idea how to neatly test this?

**Comment by leoasis** [comment]
> First, where in the changelog should I add the entry? Under 2.1.0-beta.0, or rather somewhere else?

Under **vNext**

> However, Typescript is too smart, and points out the "mistake":

In this case I think it's fair to bypass Typescript since this is a use case for plain JS users:

```ts
class MyComponent extends (React.Component as any) {
  render = () => {
    return <div>{_.times(this.props.n, i => <span key={i} />)}</div>;
  }
}
```

**Comment by leoasis** [comment]
@edorivai awesome work, thanks!

**Comment by edorivai** [comment]
:tada:

@leoasis final question, is there a plan for when a new release will be cut? We've currently disabled SSR on a couple pages until this patch lands. But if it will take a couple days before a release, we might have to look at alternative temporary solutions.

Thanks again :smile:

**Comment by leoasis** [comment]
The idea would be to release in the next couple days, so yeah it should be soon.

Regarding a workaround, why not try defining the render method in the prototype for now? You can define it as an empty function, it won't matter since the other one is defined in the instance and will be looked at first:

```js
import { Link } from 'react-scroll';

Link.prototype.render = () => {};
```

I think that should be enough

**Comment by edorivai** [comment]
@leoasis Heh, that would have been such a nice hack. Next couple days should be fine.

**Comment by leoasis** [comment]
@edorivai this is now released in 2.1.0-beta.1! https://github.com/apollographql/react-apollo/blob/master/Changelog.md#210-beta1

**Pull request merged**
