### PR TITLE
make testing more accessible with smaller files

### PR DESCRIPTION
**Pull request by jbaxleyiii**
No more > 2000 line test files 😍

### CODE REVIEW

**Comment by helfer** [comment]
@jbaxleyiii it looks like the CI failed on this one. We're getting problems upstream because apollo-client CI now fails, too!

**Comment by helfer** [comment]
Probably a good reason to not also run apollo-angular tests in apollo-client automatically :)

**Comment by jbaxleyiii** [comment]
@helfer oh no! I could have sworn it was green when I merged it! I'll revert!

**Comment by jbaxleyiii** [comment]
@helfer master is green again! I'm so sorry about that!

**Comment by helfer** [comment]
No problem at all! I wouldn't have noticed, but @cesarsolorzano was very attentive and found out right away, haha! 😄 He's working on getting the `strict writes` ready for merging! :heart:

**Comment by jbaxleyiii** [comment]
🙌🏼🙌🏼🙌🏼

**Pull request merged**
