### PR TITLE
Fix lodash.* packages - remove re-export `compose`

### LINKED ISSUE #1445: 2.0.4 requires unstated dependency @types/lodash.flowright
Error description is already in #1286 but it is closed so I open another issue because this error is also in 2.0.4 (which has been confirmed several times in #1286). 

Basically, if you just install 2.0.4 it is broken from the start with this error. The easiest work-around is to add a file `fix-react-apollo.d.ts` (the name does not matter) which contains one line `declare module "lodash.flowright";` as described in [this comment](https://github.com/apollographql/react-apollo/issues/1286#issuecomment-350591666).

### PR DESCRIPTION
**Pull request by rosskevin**
Closes #1445.  Supercedes #1474 

## Updated summary
We were re-exporting `flowright` a.k.a. `compose` which was implicitly or explicitly using the `any` type - which is not a good idea.  Instead, remove this re-export and allow users to choose their composition method on their own.

## Migration
User may migrate by:
1. `yarn add lodash @types/lodash` && using with `const compose = require('lodash/flowRight)`; or
2. `yarn add recompose @types/recompose` && using with `const compose = require('recompose/compose')`

## Other changes
- lock down bundle max size to 4.7 KB prior to change (4.67KB actual)
- remove `lodash.pick` and `lodash.flowright` packages
- use `lodash/pick` which has types in `@types/lodash`
- re-compile and check file size
- fix inconsistency with flow types `QueryProps` -> `GraphqlQueryControls`

### CODE REVIEW

**Comment by rosskevin** [comment]
I see in the `lib/index.d.ts` that compose is exported as `any`.  So while **our** usage is fully typed, we are re-exporting something as an explicit `any`.  While some might be good with it, it seems like we are dumbing down types.

**Comment by rosskevin** [comment]
@jbaxleyiii @excitement-engineer I propose we remove the re-export of `flowright` because it is dumbing down the type-checking, and we are assuming it is how users will want to compose.

**Comment by excitement-engineer** [comment]
I agree. I think the docs can point out some the various alternatives and let the user decide which to use.

**Comment by excitement-engineer** [comment]
Can you add the breaking change in the flow type name to the changelog as well? Otherwise it looks good

**Comment by rosskevin** [comment]
Already in the changelog but I'll add the second link to this issue.

**Comment by rosskevin** [comment]
@excitement-engineer tests are failing on travis only - something with imports.  I tweaked the jest config a bit but I'm at a loss.  Wiped out node_modules locally and still all good.  Wiped out cache on travis and it still fails.  Makes no sense.

**Comment by develomark** [comment]
+1 on this approach, however, I simply replaced:

```
import * as compose from 'lodash.flowright';
export { compose };
```

with

```
import { flowRight as compose} from "lodash";
export { compose };
```

in `browser.d.ts` to fix TS compile errors.

**Comment by ryanflowers** [comment]
Hello @rosskevin I see you fixed this issue and merged it to master. Thank you! I'm just wondering when it will be published in npm for consumption..

**Comment by kaanozcan** [comment]
I am also wondering when will this be released?

**Pull request merged**
