### PR TITLE
ensure state is null (not undefined) for components during walkTree

### PR DESCRIPTION
**Pull request by mattfysh**
### Checklist:

- [X] (N/A) If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [X] Make sure all of the significant new logic is covered by tests
- [X] (N/A) If this was a change that affects the external API used in GitHunt-React, update GitHunt-React and post a link to the PR in the discussion.

### CODE REVIEW

**Comment by mattfysh** [comment]
Fixes #1249

**Comment by mattfysh** [comment]
@jbaxleyiii - could you take a look at this when you get a minute? it should pass all the checks... basically I'm running into an issue with `react-emotion` due to an explicit check for null:

https://github.com/emotion-js/emotion/blob/master/packages/react-emotion/src/index.js#L82

The `react-apollo` SSR walk needs to be updated to match React behaviour, i.e. `isNull(this.state)`

**Comment by jbaxleyiii** [comment]
@mattfysh sure thing!! would you be able to rebase / cherry-pick your changes into a new branch against master? The branch swticherro from 1.0 to 2.0 happened today so the PR's will need to be updated!

**Comment by jbaxleyiii** [comment]
@mattfysh looked at the code change, it looks perfect to me! If you can clean up the PR / branch I'm thrilled to merge and release!

**Pull request closed without merging**
