### PR TITLE
Export ApolloContext to use in classes or hooks

### PR DESCRIPTION
**Pull request by MrLoh**
#2540 didn't include any way to access the apollo context and #2872 only made it into the v3 branch. By simply exposing the `ApolloContext` it can be used with `MyClassComponent.contextType = ApolloContext` or with `useContext(ApolloContext)` without having to change any react peer dependencies.

### CODE REVIEW

**Comment by FezVrasta** [comment]
This would be great to reduce the amount of code needed to run `react-apollo-hooks`, that way it will be easier to migrate to the official Hooks implementation once ready.

**Comment by MrLoh** [comment]
@hwillson any chance that this could be merged?

**Comment by FezVrasta** [comment]
When can we expect this to be released?

**Comment by hwillson** [comment]
@FezVrasta `react-apollo` 2.5.5 was just released with this change.

**Comment by FezVrasta** [comment]
Great thanks!

**Comment by FredyC** [comment]
Thanks @MrLoh. Finally, we can drop a double provider (react-apollo-hooks)!

**Comment by FezVrasta** [comment]
@FredyC I started a discussion here https://github.com/trojanowski/react-apollo-hooks/issues/131

**Pull request merged**
