### PR TITLE
Refactor dataForChild on DocumentType.Mutation to use new bound funct…

### PR DESCRIPTION
**Pull request by baerrach**
Attempt at fixing #725 

dataForChild previously returned a new function for type DocumentType.Mutation
causing React shallowEqual render optimizations to fail.

Refactored the mutation specific code into its own method with a binding to
'this' in the constructor.

Haven't create a test case for this as all the tests render nulls, and this only shows up in real use on multiple renders. I'm not enough of an expert on React and testing to know how to do this properly.

TODO:

- [X] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests
- [X] Rebase your changes on master so that they can be merged easily
- [X] Make sure all tests and linter rules pass
- [ ] Update CHANGELOG.md with your change
- [ ] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion
- [ ] If this was a change that affects GitHunt-React, update GitHunt-React and post a link to the PR in the discussion

### CODE REVIEW

**Comment by baerrach** [comment]
Yes, I'm all for writing tests with PRs.
And I need to know how to do this for my own work. So I'm keen to learn.

**Comment by jbaxleyiii** [comment]
I'd be happy to show you how to test this! I'm out of town starting tonight
so it won't be until Sunday though

**Comment by baerrach** [comment]
I'm in no rush.

I also just found [How to Fork and Patch NPM Modules](http://debuggable.com/posts/how-to-fork-patch-npm-modules:4e2eb9f3-e584-44be-b1a9-3db7cbdd56cb) so I can stop manually editing files in node_modules.

**Comment by derek-duncan** [comment]
@baerrach thanks for tackling this one. I just wanted to note that all of the functions in the `data` object create a new reference each render. Should we include these in this PR as well?

Functions in `data` response for queries.
```
data.refetch(variables)
data.fetchMore(options)
data.subscribeToMore(options)
data.startPolling(interval)
data.stopPolling()
data.updateQuery(updaterFn)
```

**Comment by baerrach** [comment]
Yes, its a can of worms that needs looking at thoroughly.
Its probably not my area of expertise those, so if you can find someone who has the time and knowledge it would be best to get them to look over the code base with that in mind.

First step might be to write tests to make sure things aren't re-rendering unnecessarily, then that will give people a list of things to work on. 

With a set of guidelines in place on how to resolve the typical issues other people should be able to chip in and fix it up bit by bit.

**Pull request merged**
