### PR TITLE
convert React.PropTypes to "prop-types" module

### LINKED ISSUE #623: Convert React.PropTypes to PropTypes provided by prop-types package
Hi there, 

Just following your contributing guidelines. I'm able to submit a PR for this if you decide that's okay for me to do.

I'm sure you're all aware that React 15.5 deprecates `React.PropTypes` and moves it to its own module. Would this be something you are all okay with me doing in a PR?

Not a dire issue by any means, but it is somewhat annoying to see the console.error messages in my CI pipeline.

Thanks so much! Also, thanks for all your work on the Apollo project in general. 👍 👍

### PR DESCRIPTION
**Pull request by dsifford**
Closes #623 

TODO:

- (**N/A**) If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- (**N/A**) Make sure all of the significant new logic is covered by tests
- [ ] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change
- (**N/A**) If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

**Note:** There's a significant amount of existing lint errors in the test files, but I skipped over them since that is outside the scope of this PR. None are build-breaking because those files aren't actually linted during CI.

### CODE REVIEW

**Comment by stubailo** [comment]
This looks great to me.

**Comment by stubailo** [comment]
@dsifford thanks for contributing!

**Comment by happylinks** [comment]
Is this released correctly? 1.0.2 doesn't seem to have these fixes.

**Comment by dacz** [comment]
yes, 1.0.2 still has warnings, unfortunatelly

**Comment by ryancole** [comment]
In my bundle, the code here appears to still be pulling prop types from react.

https://github.com/apollographql/react-apollo/blob/0754776cce7d315af7b0ff18b52004553c8a4e47/src/ApolloProvider.tsx#L22-L31

**Comment by VladShcherbin** [comment]
It was merged after 1.0.2, using master branch is an option to prevent annoying warnings.

**Comment by caffo** [comment]
Any chance of getting a new version released? I want to upgrade react and the warnings are blocking it.  😄

**Comment by helfer** [comment]
There's a warning in one of the tests (even though they all pass) that I want to look into. I'll try to release a new version before the weekend.

**Comment by dsifford** [comment]
Sorry, everybody! Figured converting the deprecations in just `react-apollo` would cause the warnings to disappear, but clearly, that was not the case.

@helfer Let me know if there's something I can do to help. I feel like this PR is not in good form since its sole purpose has not actually been achieved.

**Comment by MichaelDeBoey** [comment]
@dsifford If you have refactored every `React.PropTypes` call to the new `PropTypes` call, that's all you can do in this repo.
But it's possible you still get the warnings because of dependencies haven't updated their codebase yet.

**Pull request merged**
