### PR TITLE
fix: refactor imports/exports to play nicely with webpack

### LINKED ISSUE #1409: getDataFromTree not playing well with webpack
Issue: We are getting an error in the browser:

```
Uncaught TypeError: Cannot redefine property: getDataFromTree
   at Function.defineProperty (<anonymous>)
   at Object.<anonymous> (lib-7fd04c4927421371.js:1)
   at t (lib-7fd04c4927421371.js:1)
   at Object.92 (app-7fd04c4927421371.js:1)
   at t (lib-7fd04c4927421371.js:1)
   at Object.91 (app-7fd04c4927421371.js:1)
   at t (lib-7fd04c4927421371.js:1)
   at Object.<anonymous> (app-7fd04c4927421371.js:1)
   at Object.622 (app-7fd04c4927421371.js:1)
   at t (lib-7fd04c4927421371.js:1)```
```

We found that this issue is related to some module imports/exports in the [server.ts](https://github.com/apollographql/react-apollo/blob/master/src/server.ts)

```
...
import { getDataFromTree } from './getDataFromTree';
export * from './getDataFromTree';
...
```

It appears that there is a collision with getDataFromTree when exporting. We've only seen this issue occur when using webpack to bundle up components for an app.

### PR DESCRIPTION
**Pull request by rjanjua**
Fixes #1409 

Issue: We were getting an error in the browser:

```
Uncaught TypeError: Cannot redefine property: getDataFromTree
   at Function.defineProperty (<anonymous>)
   at Object.<anonymous> (lib-7fd04c4927421371.js:1)
   at t (lib-7fd04c4927421371.js:1)
   at Object.92 (app-7fd04c4927421371.js:1)
   at t (lib-7fd04c4927421371.js:1)
   at Object.91 (app-7fd04c4927421371.js:1)
   at t (lib-7fd04c4927421371.js:1)
   at Object.<anonymous> (app-7fd04c4927421371.js:1)
   at Object.622 (app-7fd04c4927421371.js:1)
   at t (lib-7fd04c4927421371.js:1)```
```

We found that this issue is related to some module imports/exports in the [server.ts](https://github.com/apollographql/react-apollo/blob/master/src/server.ts)

```
...
import { getDataFromTree } from './getDataFromTree';
export * from './getDataFromTree';
...
```

It appears that there is a collision with getDataFromTree when exporting. We've only seen this issue occur when using webpack to bundle up components for an app.

The fix we put in is to remove the `export * from './getDataFromTree';` from server.ts and import getDataFromTree and walkTree into index.ts.

### Checklist:

- [x] Make sure all of the significant new logic is covered by tests
No new logic, just a change in imports

### CODE REVIEW

**Comment by kaliabadi** [comment]
I agreed dunno why it's saying that :(

**Comment by rjanjua** [comment]
looks like this has been fixed already in #1402

**Comment by rosskevin** [comment]
Thanks @rjanjua - #1402 was merged with the fix - though not yet released.  We'll have a new release after the 1st of the year.

**Comment by massimonewsuk** [comment]
I tried the `2.1.0-beta.3` release from NPM and I still get the `Uncaught TypeError: Cannot redefine property: getDataFromTree` error.

Full stack trace as follows:
```
Unhandled rejection TypeError: Cannot redefine property: getDataFromTree
    at Function.defineProperty (<anonymous>)
    at Object.defineProperty.value (PROJECT_ROOT/src/dist/something.bundle.js:949:328)
    at __webpack_require__ (PROJECT_ROOT/src/dist/something.bundle.js:30:30)
    at Object.defineProperty.value (PROJECT_ROOT/src/dist/something.bundle.js:1626:1047)
    at __webpack_require__ (PROJECT_ROOT/src/dist/something.bundle.js:30:30)
    at Object.<anonymous> (PROJECT_ROOT/src/dist/something.bundle.js:1570:314)
    at __webpack_require__ (PROJECT_ROOT/src/dist/something.bundle.js:30:30)
    at Object.<anonymous> (PROJECT_ROOT/src/dist/something.bundle.js:1535:53)
    at __webpack_require__ (PROJECT_ROOT/src/dist/something.bundle.js:30:30)
    at PROJECT_ROOT/src/dist/something.bundle.js:73:18
    at PROJECT_ROOT/src/dist/something.bundle.js:11:17
    at webpackUniversalModuleDefinition (PROJECT_ROOT/src/dist/something.bundle.js:3:20)
    at Object.<anonymous> (PROJECT_ROOT/src/dist/something.bundle.js:1:1)
    at Module._compile (module.js:643:30)
    at loader (PROJECT_ROOT\src\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (PROJECT_ROOT\src\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (PROJECT_ROOT/src/lib/react-renderers/something-else.js:4:17)
    at Module._compile (module.js:643:30)
    at loader (PROJECT_ROOT\src\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (PROJECT_ROOT\src\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

Happy to provide more info if needed.

**Pull request closed without merging**
