### PR TITLE
Use a Map of Providers to handle SSR React 16 context

### LINKED ISSUE #2135: getDataFromTree not correctly resetting context providers
**Intended outcome:**
When using getDataFromTree, the context providers should be correctly reset to their initial value before the final React.renderToString call is executed

**Actual outcome:**
Context providers hold their last set value

**How to reproduce the issue:**
https://github.com/Torsten85/apollo-getDataFromTree

this repo should log:
```
Render #1 <div>Initial: 1<div>Nested Initial: 2</div></div>
Render #2 <div>Initial: 1<div>Nested Initial: 2</div></div>
Render #3 <div>Initial: 1<div>Nested Initial: 2</div></div>
```

but actually logs:
```
Render #1 <div>Initial: 1<div>Nested Initial: 2</div></div>
Render #2 <div>Initial: 1<div>Nested Initial: 2</div></div>
Render #3 <div>Initial: 2<div>Nested Initial: 3</div></div>
```

**Version**

* apollo-client@2.3.5
* react-apollo@2.1.6

### LINKED ISSUE #2139: getDataFromTree is messing up context values
**Intended outcome:**
I'm using the new React Context API to keep a "tree path" and that value is used to choose which components will be rendered. Some of them may have graphql queries that should run on server side. That was working as intended using the old React Context API.

**Actual outcome:**
`getDataFromTree` is messing up context values and that is impacting directly on my server side rendering.

I think it is related to #2135.

**How to reproduce the issue:**
https://github.com/brunoabreu/getDataFromTree-context-bug

This repo has this `Node` component that is a context consumer and provider at same time.

```js
const App = (
  <Node id='root'>
    <Node id='one'>
      <Node id='a' />
      <Node id='b' />
    </Node>
    <Node id='two'>
      <Node id='a' />
      <Node id='b' />
    </Node>
  </Node>
)
```

It works as expected with `ReactDom.renderToStaticMarkup`, but not with `getDataFromTree`:

```
without getDataFromTree:
ID: root | PARENT:
ID: one | PARENT: root
ID: a | PARENT: root/one
ID: b | PARENT: root/one
ID: two | PARENT: root
ID: a | PARENT: root/two
ID: b | PARENT: root/two

during getDataFromTree:
ID: root | PARENT:
ID: one | PARENT: root
ID: a | PARENT: root/one
ID: b | PARENT: root/one/a
ID: two | PARENT: root/one/a/b
ID: a | PARENT: root/one/a/b/two
ID: b | PARENT: root/one/a/b/two/a
```

**Version**

* apollo-client@2.3.5
* react-apollo@2.1.6

### LINKED ISSUE #2291: getDataFromTree visits React 16.3 context, but does not actually set the value in the context
**Intended outcome:**

I am storing query variables inside the React 16.3 context, and passing them to my Query component. This works as expected on the client side, but when rendering on the server side, getDataFromTree does not update the context value. 

**Actual outcome:**

The context value is never updated, the default set at the start is used everywhere

**How to reproduce the issue:**

```
import * as React from 'react';

import { getDataFromTree } from 'react-apollo';

const TestContext = React.createContext({ test: 'defaultValueSetByHardcode' });
const TestChildren = () => {
  return (
    <TestContext.Consumer>
      {({ test }) => {
        console.log('Consume value in TestChildren', { test });
        return (<pre>{ test }</pre>);
      }}
    </TestContext.Consumer>
  );
};

const TestParent = () => {
  console.log('Rendering TestParent, providing test = valueSetByProvider ')
  return (
    <TestContext.Provider value={{ test: 'valueSetByProvider'}}>
      <TestChildren/>
    </TestContext.Provider>
  );
};

getDataFromTree(<TestParent/>, {}).then(() => {
  console.log('Getting data does not update the context');
});
```

Running that will log to the terminal the following lines:

```
Rendering TestParent, providing test = valueSetByProvider 
Consume value in TestChildren { test: 'defaultValueSetByHardcode' }
Getting data does not update the context
```

**Version**

* apollo-client@2.3.5
* react-apollo@2.1.11

### PR DESCRIPTION
**Pull request by tgriesser**
A different approach than #2304, which was giving me errors when trying it out. The current approach of mutating the context objects seems like it's causing issues - this takes a different approach.

This fixes React.createContext by caching the Provider value on the context as the tree is walked, so the context can be accessed by children further down the tree. Currently requires that the `ApolloProvider` is the top-level, before any other React context elements.

I used the legacy context API via `ApolloProvider`, but could also move this all into the `getDataFromTree` if that seems clearer.

Closes #2291
Closes #2135
Closes #2139

### Checklist:

* [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
* [x] Make sure all of the significant new logic is covered by tests
* [x] If this was a change that affects the external API used in GitHunt-React, update GitHunt-React and post a link to the PR in the discussion.

### CODE REVIEW

**Comment by mitchellhamilton** [comment]
This doesn't completely fix the issue as the incorrect value will still be used when Apollo is calling render on things. If you try the test below on the implementation here, you'll see that they fail.
While #2304 and the current implementation both mutate the context object, #2304 sets currentValue back to it's original value so it's as if it didn't do anything so I don't see how it could cause any errors.

Also, I'm curious, what errors did you get with #2304?
```jsx
let defaultValue = "default";
let Context = React.createContext(defaultValue);
let providerValue = "provider";

expect(
  await renderToStringWithData(
    <React.Fragment>
      <Context.Provider value={providerValue} />
      <Context.Consumer>
        {val => {
          expect(val).toBe(defaultValue);
          return val;
        }}
      </Context.Consumer>
    </React.Fragment>
  )
).toBe(defaultValue);

expect(
  await renderToStringWithData(
    <Context.Provider value={providerValue}>
      <Context.Consumer>
        {val => {
          expect(val).toBe(providerValue);
          return val;
        }}
      </Context.Consumer>
    </Context.Provider>
  )
).toBe(providerValue);

expect(
  await renderToStringWithData(
    <Context.Consumer>
      {val => {
        expect(val).toBe(defaultValue);
        return val;
      }}
    </Context.Consumer>
  )
).toBe(defaultValue);
```

**Comment by tgriesser** [comment]
@mitchellhamilton I believe the issue is that `getDataFromTree` is asynchronous:

https://github.com/apollographql/react-apollo/blob/bbbb2c58e87d25a893293f0288d9586a5b160a1f/src/getDataFromTree.ts#L195-L203

So in your PR, on the first pass the context is set correctly, but then is lost and reset to default when tree is walked further after the `fetchData` promises are resolved.

**Comment by tgriesser** [comment]
@mitchellhamilton fixed the implementation so it should cover your additional test case. Let me know if there's something it looks like I'm missing.

**Comment by mitchellhamilton** [comment]
While getDataFromTree is asynchronous, the tree walking is not.

It goes like this, walk tree to find promises -> wait for promises to resolve -> render by react.

Could you explain what cases this is actually solving over #2304?

**Comment by tgriesser** [comment]
I’ll work on a test case, but IIRC the issue seemed to be:

walk tree to find promises -> wait for promises to resolve -> walk tree further to find more promises -> repeat until there are no promises -> render by react

The context seemed to be lost if there are multiple levels of walking.

**Comment by mitchellhamilton** [comment]
Ohhhhhh, I totally get it now. The implementation here doesn't seem to have any fixes for the tests I showed though (I can't see any new commits) so I updated my implementation to use Maps though it doesn't use the old context and importantly it clones the map when it reaches a provider so only children have that context value.

**Comment by tgriesser** [comment]
I had added the update with your test above in this commit https://github.com/apollographql/react-apollo/pull/2314/commits/137077d06e4cec542ec7f698c1789e8e0a9cec8c (and then force pushed which might have made it seem like there weren't updates). It too clones the Map so children only see the proper context.

I don't really care which gets merged, they both seem to fix the problem - I do like how yours adds a separate variable to track the "new" context rather than taking it on to the existing one. Added a note on your PR with a change that's needed to match up with the context spec.

**Comment by tgriesser** [comment]
@mitchellhamilton by the way, thanks for your work on emotion-js. I have been using it in my projects and it's awesome!

**Comment by mitchellhamilton** [comment]
I don't really mind much which gets merged either, I just added some more tests though which might be helpful.

> @mitchellhamilton by the way, thanks for your work on emotion-js. I have been using it in my projects and it's awesome!

Thanks! ❤️

**Comment by elmpp** [comment]
Looking good, great news people

**Comment by elmpp** [comment]
Hello people, is there any movement here?

**Comment by hwillson** [comment]
Thanks for working on this @tgriesser! We've decided to merge in https://github.com/apollographql/react-apollo/pull/2304, but your work here has helped move that PR forward. Thanks again!

**Pull request closed without merging**
