### PR TITLE
Prettier

### PR DESCRIPTION
**Pull request by jbaxleyiii**
### Added auto formatting via prettier!

TODO:
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change

### CODE REVIEW

**Comment by stubailo** [comment]
O M G    Y E S

**Comment by stubailo** [comment]
James you're really racking up the LOCs quickly, super productive

**Comment by stubailo** [comment]
If we have prettier and TypeScript, do we actually need TSLint? I wonder if it checks for anything that isn't covered by those two.

**Comment by jbaxleyiii** [comment]
@stubailo TSLint enforces some best practices, helps catch more runtime specific stuff (like variable declared after usages for instance). In my experience, prettier + a linter that isn't focused on style is really wonderful.

**Comment by jbaxleyiii** [comment]
I'm going to close this for now until all open PR's are merged through so I don't force a contributor to rebase on top of this 😨 

Then I'll open it back up with everything super pretty 💅

**Pull request closed without merging**
