### PR TITLE
Make ChildProps.data non-optional

### PR DESCRIPTION
**Pull request by choffmeister**
Please see issue #1083

### CODE REVIEW

**Comment by leoasis** [comment]
I think you also need to update `OptionProps` defined above https://github.com/apollographql/react-apollo/pull/1143/files#diff-41df78d86ed4de80aae9b0b9560feb2bL65

**Comment by choffmeister** [comment]
True thx. Still there are tests failing which is weired, since I did not change any actual code. Also the tests suite does also not run through locally on `master` branch...

**Comment by leoasis** [comment]
The build fail seems to be related to some typescript checks that now fail because of the changed types: https://travis-ci.org/apollographql/react-apollo/builds/279954551#L773

**Comment by choffmeister** [comment]
OK, these error is from making `data` optional also on `OptionProps`. Before there was no typing error but just some unit tests failed. Will have to look into it.

**Comment by choffmeister** [comment]
@leoasis I reverted the part for `OptionProps` so this is at least correct for now. I am also not really sure that `OptionProps.data` is indeed optional. At least how it is implemented now it is not.

**Comment by leoasis** [comment]
Hmm I think `data` can be optional in both cases, since you won't get it either in `ChildProps` when you set up a mutation.

**Comment by leoasis** [comment]
I think this one is a bit hard to typecheck, since the decision on wether this HoC acts as a mutation or as a query, really depends on the graphql Document that is passed to it, and it's determined at runtime.

**Comment by jbaxleyiii** [comment]
I had no idea this even existed! So cool!

**Comment by jbaxleyiii** [comment]
hmm these test failures seem to be everywhere? I wonder what it is. Anyhow, its not related to this PR so I'll merge this through!

**Comment by leoasis** [comment]
@jbaxleyiii but won't data be undefined if we just use `graphql` for a mutation? I guess that why it was optional in the first place.

Also, I think `OptionProps` here https://github.com/apollographql/react-apollo/pull/1143/files#diff-41df78d86ed4de80aae9b0b9560feb2bL65 should have the same `Partial` treatment to `TResult`

**Pull request merged**
