### PR TITLE
return data when Query Component skip prop is set

### PR DESCRIPTION
**Pull request by 7yp0**
Related to this: https://github.com/apollographql/react-apollo/issues/1811

### CODE REVIEW

**Comment by danilobuerger** [comment]
This is working as expected. `data` is either `TData` or `undefined`. Since we are skipping, `data` is set to undefined. 

See also comment in source:
```
    // When skipping a query (ie. we're not querying for data but still want
    // to render children), make sure the `data` is cleared out and
    // `loading` is set to `false` (since we aren't loading anything).
```

**Comment by danilobuerger** [comment]
@7yp0 You could use `fetchPolicy` for that. For example: set it to cache first (which is the default anyway) and if you want to update call a refetch until you don't anymore.

**Comment by 7yp0** [comment]
I tried that already, but sadly it won't work for my special case, since the caching is not working for this query (long story... the issue here is probably that we failed at chunking the query properly. Instead we have one huge query, which fucks up caching of course)

I had hoped to solve (work around) this with the skip property but as you mentioned it is not supposed to be as I expected.

Thanks for your clarification.

**Comment by danilobuerger** [comment]
Best bet is to ask on Slack about it, I bet someone can help you.

**Pull request closed without merging**
