### PR TITLE
added sugar for graphql

### PR DESCRIPTION
**Pull request by jbaxleyiii**
Is this useful to anyone? Does it make things more confusing?

cc @helfer @stubailo 

TODO:
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change

### CODE REVIEW

**Comment by stubailo** [comment]
Hmm this is odd, we should at least make sure it validates the correct type of operation

**Comment by jbaxleyiii** [comment]
@stubailo haha for sure! I just wanted to push this out to see if it was actually useful or if it would make things more confusing (greater surface area) for people

**Comment by stubailo** [comment]
I do think this makes sense now that I think about it since what you actually get in the props is so different for mutations vs queries.

**Comment by eug48** [comment]
These might be useful to further improve the great work done recently on TypeScript support. In particular some common properties are currently optional (e.g. `data` & `mutate`) so strictNullChecks needs to be needlessly overridden (i.e. in the `props` function have to use `data!.loading` instead of `data.loading`).

**Comment by jbaxleyiii** [comment]
@eug48 @stubailo I'm going to continue to pursue this direction! However, with the upcoming prettier PR, plus a few others, this will be out of date and there wasn't really any meat here anyway. I'm going to close it and revisit it soon!

**Pull request closed without merging**
